name: Build Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
      
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - uses: azure/docker-login@v1
      - name: Docker Connect
        with:
          login-server: https://hub.docker.com/
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PWDDOCKERHUB }}

      - name: Build the Docker image
        run: |
         docker build . --file Dockerfile --tag julianorinaldi/design-patterns-github:latest
      - name: Docker Push
        run: |
         docker push julianorinaldi/design-patterns-github:latest